vich_uploader:
    db_driver: orm
    
    metadata: 
        type: attribute

    mappings:
        annonce_images:
            uri_prefix: /images/annonces
            upload_destination: '%kernel.project_dir%/public/images/annonces'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: false
            delete_on_remove: true